mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'), # для представления на основе функции
    # path('', views.PostListView.as_view(), name='post_list'), # для представления на основе класса
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', # использовать дату публикации и слаг для URL-адреса
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = { # передается в представление sitemap
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.itemap'),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                            .filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices): 
        DRAFT = 'DF', 'Daft' # черновик поста
        PUBLISHED = 'PB', 'Published' # варианты статуса, пары "значение-метка"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, # короткая метка
                            unique_for_date='publish') # поле slug должно быть уникальным для даты, сохраненной в поле publish, чтобы избежать дублирование записей

    author = models.ForeignKey(User,
                               on_delete=models.CASCADE, # при удалении пользователя удалятся все его посты
                               related_name='blog_posts') # для обращения к объектам из объекта User, используя обозначение user.blog_posts
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True) # дата будет обновляться автоматически
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    
    objects = models.Manager() # manager by default
    published = PublishedManager() # the new one

    tags = TaggableManager() # менеджер, к-й позволяет добавлять, извлекать и удалять теги из объектов Post

    class Meta: # метаданные модели
        ordering = ['-publish'] # если в запросе не указан порядок сортировки постов, задается обратный порядок (сначала новые) по полю publish
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self): # формирует URL-адрес динамически; используется для формирования адреса в карте сайта
        return reverse("blog:post_detail", args=[self.publish.year, # позиционный аргумент
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, # пост, к к-му написан комментарий, можно извлекать с помощью comment.post
                             on_delete=models.CASCADE,
                             related_name='comments') # для обращения к комментариям из объектов Post с помощью post.comments.all()
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True) # дата при создании объекта
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) # по умолчанию все комментарии активны, удалять комментари можно с сайта администрирования

    class Meta:
        ordering = ['-created'] # сортировать в хронологическом порядке
        indexes = [
            models.Index(fields=['-created']), # индексировать в возрастающем порядке
        ]
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25) # имя человека, отпраляющего пост
    email = forms.EmailField() # почта отправителя
    to = forms.EmailField() # почта получателя
    comments = forms.CharField(required=False, # является опциональным
                               widget=forms.Textarea) # комментарий вставляется в письмо
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment # чтобы создать форму из модели
        fields = ['name', 'email', 'body'] # включить только эти поля

class SearchForm(forms.Form):
    query = forms.CharField() # используется, чтобы давать пользователям возможность вводить поисковые запросы

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from config import EMAIL_HOST_USER
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector

'''Представление на основе класса для отображения списка постов

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = 'blog/post/list.html'
'''

'''
Представление на основе функции для отображения списка постов
'''
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    
    tag = None

    if tag_slug: # фильтровать посты по тегу
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 4) # отображать по 4 поста на страницу
    page_number = request.GET.get('page', 1) # GET-параметр page содержит запрошенный номер страницы. Если его нет, загрузить первую страницу результатов
    
    try:
        posts = paginator.page(page_number) # передаем номер страницы и объект posts в шаблон
    except PageNotAnInteger:
        posts = paginator.page(1) # Если запрошенная страница не является целым числом, вернуть первую страницу результатов
    except EmptyPage:
        posts = paginator.page(paginator.num_pages) # Если запрошенная страница находится вне диапазона, вернуть последнюю страницу результатов

    return render(request, 'blog/post/list.html',
                  {'posts': posts, # 'Page' object
                   'page_number': int(page_number),
                   'tag': tag})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, 
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    
    comments = post.comments.filter(active=True) # список активных комментариев к этому посту (queryset)

    form = CommentForm() # форма для комментиррования пользователями

    post_tags_ids = post.tags.values_list('id', flat=True) # теги текущего поста
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id) # список похожих постов с такими же тегами
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:3] # последние посты 

    return render(request, 'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form,
                   'similar_posts': similar_posts})

def post_share(request, post_id):
    # извлечь пост по id
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST': # передать форму на обработку
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri( # ссылка на пост вставляется в письмо
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read" \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments:{cd['comments']}"
            send_mail(subject, message, f'{EMAIL_HOST_USER}', [cd['to']])
            sent = True

    else: # отобразить пустую форму
        form = EmailPostForm()

    return render(request, 'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent})

# разрешить запросы методом POST только для этого представления
@require_POST
def post_comment(request, post_id): # передача поста на обработку
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    comment = None
    # комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False) # создать объект класса Comment, не сохраняя его в бд (метод save() доступен для FormModel, но не для Form)
        comment.post = post # пост назначается созданному комментарию
        comment.save() # сохранить комментарий в бд

    return render(request, 'blog/post/includes/comment.html',
                  {'post': post,
                    'form': form,
                    'comment': comment})

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                search=SearchVector('title', 'body'),
            ).filter(search=query)

    return render(request, 'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

mysite/blog/templates/blog/post/includes/comment.html
{% load static %}
<head>
	<!-- Fuentes de Google -->
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
	<!-- Iconos -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "/css/comments.css" %}">

</head>
<body>
	{% if comment %}
	<div class="added">
		<p>Has been added</p>
	 <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
	</div>
	 
	 {% else %}
    {% include "blog/post/includes/comment_form.html" %}

<!-- partial:index.partial.html -->
<!-- Contenedor Principal -->
	<div class="comments-container">
		<h1>
			{% with comments.count as total_comments %} <!-- comments.count() - ORM-преобразователь, with - присваивать значение новой переменной -->
				<p>{{ total_comments }} comment{{ total_comments|pluralize }}</p> <!-- pluralize - отобразить суффикс множественного числа -->
			{% endwith %} </h1>
		{% for comment in comments %}
		<ul id="comments-list" class="comments-list">
			
			<li>
				<div class="comment-main-level">
					<!-- Avatar -->
					<div class="comment-avatar"><img src="http://i9.photobucket.com/albums/a88/creaticode/avatar_1_zps8e1c80cd.jpg" alt=""></div>
					<!-- Contenedor del Comentario -->
					<div class="comment-box">
						<div class="comment-head">
							<h6 class="comment-name by-author"><a href="http://creaticode.com/blog">{{ comment.name }}</a></h6>
							<span>{{ comment.created }}</span>
							<i class="fa fa-reply"></i>
							<i class="fa fa-heart"></i>
						</div>
						<div class="comment-content">
							{{ comment.body|linebreaks }}
						</div>
					</div>
				</div>
				<!-- Respuestas de los comentarios 
				<ul class="comments-list reply-list">
					<li>
						<!-- Avatar 
						<div class="comment-avatar"><img src="http://i9.photobucket.com/albums/a88/creaticode/avatar_2_zps7de12f8b.jpg" alt=""></div>
						<!-- Contenedor del Comentario 
						<div class="comment-box">
							<div class="comment-head">
								<h6 class="comment-name"><a href="http://creaticode.com/blog">Lorena Rojero</a></h6>
								<span>hace 10 minutos</span>
								<i class="fa fa-reply"></i>
								<i class="fa fa-heart"></i>
							</div>
							<div class="comment-content">
								Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit omnis animi et iure laudantium vitae, praesentium optio, sapiente distinctio illo?
							</div>
						</div>
					</li>

					<li>
						<!-- Avatar 
						<div class="comment-avatar"><img src="http://i9.photobucket.com/albums/a88/creaticode/avatar_1_zps8e1c80cd.jpg" alt=""></div>
						<!-- Contenedor del Comentario 
						<div class="comment-box">
							<div class="comment-head">
								<h6 class="comment-name by-author"><a href="http://creaticode.com/blog">Agustin Ortiz</a></h6>
								<span>hace 10 minutos</span>
								<i class="fa fa-reply"></i>
								<i class="fa fa-heart"></i>
							</div>
							<div class="comment-content">
								Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit omnis animi et iure laudantium vitae, praesentium optio, sapiente distinctio illo?
							</div>
						</div>
					</li>
				</ul>-->
			</li>
			
		</ul>
		{% empty %}
			<p>There are no comments.</p>
		{% endfor %}
	</div>
<!-- partial -->
  {% endif %}
</body>

mysite/blog/templates/blog/post/includes/comment_form.html
<div class="fill">

    <form action="{% url "blog:post_comment" post.id %}" method="post">
        <div class="input">
            <label>Name</label>
            {{ form.name }}
        </div>
        <div class="input">
            <label>Email</label>
            {{ form.email }}
        </div>
        <div class="input">
            <label>Text</label>
            {{ form.body }}
        </div>
        {% csrf_token %}
        <div class="submit">
            <div>
              <input class="submit-card" type="submit" value="Add comment">
            </div>
          </div>
    </form>
</div>

mysite/blog/templates/blog/post/includes/pagination.html
{% block css %}
<style>
    /* pagination position styling */
    .pagination_section {
        position: relative;
    }
     
    /* pagination styling */
    .pagination_section a {
        color: black;
        padding: 10px 18px;
        text-decoration: none;
    }
     
    /* pagination hover effect on non-active */
    .pagination_section a:hover:not(.active) {
        background-color: #031F3B;
        color: white;
    }
     
    /* pagination hover effect on active*/
     
    a.active {
        background-color: green;
        color: white;
    }
</style>
{% endblock %}

{% block content %}
<div class="container font-sans mt-8 p-4 md:p-14 text-center">
    <!-- pagination elements -->
    <div class="pagination_section">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}"><< Previous</a>
        <a href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a>
        {% endif %}

        <a href="#" class="active" >{{ page.number }}</a>
        
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a>
        <a href="?page={{ page.next_page_number }}">Next >></a>
        {% endif %}
    </div>
</div>
{% endblock %}

mysite/blog/templates/blog/post/includes/subscribe.html
{% block content %}
<!--Subscribe-->	
<div class="container font-sans bg-green-100 rounded mt-8 p-4 md:p-24 text-center">
    <h2 class="font-bold break-normal text-2xl md:text-4xl">
        <a href='{% url "blog:post_feed" %}' class="hover:underline">
            Subscribe to Ghostwind CSS</a></h2>
    <h3 class="font-bold break-normal font-normal text-gray-600 text-base md:text-xl">Get the latest posts delivered right to your inbox</h3>
    <div class="w-full text-center pt-4">
        <form action="#">
            <div class="max-w-xl mx-auto p-1 pr-0 flex flex-wrap items-center">
                <input type="email" placeholder="youremail@example.com" class="flex-1 appearance-none rounded shadow p-3 text-gray-600 mr-2 focus:outline-none">
                <button type="submit" class="flex-1 mt-4 md:mt-0 block md:inline-block appearance-none bg-green-500 text-white text-base font-semibold tracking-wider uppercase py-4 rounded shadow hover:bg-green-400">Subscribe</button>
            </div>
        </form>
    </div>
</div>
<!-- /Subscribe-->

<!--Author-->
<div class="flex w-full items-center font-sans p-8 md:p-24">
    <img class="w-10 h-10 rounded-full mr-4" src="http://i.pravatar.cc/300" alt="Avatar of Author">
    <div class="flex-1">
        <p class="text-base font-bold text-base md:text-xl leading-none">Ghostwind CSS</p>
        <p class="text-gray-600 text-xs md:text-base">Tailwind CSS version of Ghost's Casper theme by <a class="text-gray-800 hover:text-green-500 no-underline border-b-2 border-green-500" href="https://www.tailwindtoolbox.com">TailwindToolbox.com</a></p>
    </div>
    <div class="justify-end">
    <a href="post.html" class="bg-transparent border border-gray-500 hover:border-green-500 text-xs text-gray-500 hover:text-green-500 font-bold py-2 px-4 rounded-full">Read More</a>
    </div>
</div>
<!--/Author-->
{% endblock %}