mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'), # для представления на основе функции
    # path('', views.PostListView.as_view(), name='post_list'), # для представления на основе класса
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', # использовать дату публикации и слаг для URL-адреса
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = { # передается в представление sitemap
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.itemap'),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                            .filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices): 
        DRAFT = 'DF', 'Daft' # черновик поста
        PUBLISHED = 'PB', 'Published' # варианты статуса, пары "значение-метка"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, # короткая метка
                            unique_for_date='publish') # поле slug должно быть уникальным для даты, сохраненной в поле publish, чтобы избежать дублирование записей

    author = models.ForeignKey(User,
                               on_delete=models.CASCADE, # при удалении пользователя удалятся все его посты
                               related_name='blog_posts') # для обращения к объектам из объекта User, используя обозначение user.blog_posts
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True) # дата будет обновляться автоматически
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    
    objects = models.Manager() # manager by default
    published = PublishedManager() # the new one

    tags = TaggableManager() # менеджер, к-й позволяет добавлять, извлекать и удалять теги из объектов Post

    class Meta: # метаданные модели
        ordering = ['-publish'] # если в запросе не указан порядок сортировки постов, задается обратный порядок (сначала новые) по полю publish
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self): # формирует URL-адрес динамически; используется для формирования адреса в карте сайта
        return reverse("blog:post_detail", args=[self.publish.year, # позиционный аргумент
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, # пост, к к-му написан комментарий, можно извлекать с помощью comment.post
                             on_delete=models.CASCADE,
                             related_name='comments') # для обращения к комментариям из объектов Post с помощью post.comments.all()
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True) # дата при создании объекта
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) # по умолчанию все комментарии активны, удалять комментари можно с сайта администрирования

    class Meta:
        ordering = ['-created'] # сортировать в хронологическом порядке
        indexes = [
            models.Index(fields=['-created']), # индексировать в возрастающем порядке
        ]
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25) # имя человека, отпраляющего пост
    email = forms.EmailField() # почта отправителя
    to = forms.EmailField() # почта получателя
    comments = forms.CharField(required=False, # является опциональным
                               widget=forms.Textarea) # комментарий вставляется в письмо
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment # чтобы создать форму из модели
        fields = ['name', 'email', 'body'] # включить только эти поля

class SearchForm(forms.Form):
    query = forms.CharField() # используется, чтобы давать пользователям возможность вводить поисковые запросы

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from config import EMAIL_HOST_USER
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector

'''Представление на основе класса для отображения списка постов

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = 'blog/post/list.html'
'''

'''
Представление на основе функции для отображения списка постов
'''
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    
    tag = None

    if tag_slug: # фильтровать посты по тегу
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 4) # отображать по 4 поста на страницу
    page_number = request.GET.get('page', 1) # GET-параметр page содержит запрошенный номер страницы. Если его нет, загрузить первую страницу результатов
    
    try:
        posts = paginator.page(page_number) # передаем номер страницы и объект posts в шаблон
    except PageNotAnInteger:
        posts = paginator.page(1) # Если запрошенная страница не является целым числом, вернуть первую страницу результатов
    except EmptyPage:
        posts = paginator.page(paginator.num_pages) # Если запрошенная страница находится вне диапазона, вернуть последнюю страницу результатов

    return render(request, 'blog/post/list.html',
                  {'posts': posts, # 'Page' object
                   'page_number': int(page_number),
                   'tag': tag})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, 
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    
    comments = post.comments.filter(active=True) # список активных комментариев к этому посту (queryset)

    form = CommentForm() # форма для комментиррования пользователями

    post_tags_ids = post.tags.values_list('id', flat=True) # теги текущего поста
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id) # список похожих постов с такими же тегами
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:3] # последние посты 

    return render(request, 'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form,
                   'similar_posts': similar_posts})

def post_share(request, post_id):
    # извлечь пост по id
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST': # передать форму на обработку
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri( # ссылка на пост вставляется в письмо
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read" \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments:{cd['comments']}"
            send_mail(subject, message, f'{EMAIL_HOST_USER}', [cd['to']])
            sent = True

    else: # отобразить пустую форму
        form = EmailPostForm()

    return render(request, 'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent})

# разрешить запросы методом POST только для этого представления
@require_POST
def post_comment(request, post_id): # передача поста на обработку
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    comment = None
    # комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False) # создать объект класса Comment, не сохраняя его в бд (метод save() доступен для FormModel, но не для Form)
        comment.post = post # пост назначается созданному комментарию
        comment.save() # сохранить комментарий в бд

    return render(request, 'blog/post/includes/comment.html',
                  {'post': post,
                    'form': form,
                    'comment': comment})

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                search=SearchVector('title', 'body'),
            ).filter(search=query)

    return render(request, 'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

mysite/blog/templates/blog/post/latest_posts.html
<!--Posts-->			

<!--Lead Card-->

<div class="flex h-full bg-white rounded overflow-hidden shadow-lg">
    <div class="w-full md:w-2/3 rounded-t">	
        <img src="https://source.unsplash.com/collection/494263/800x600" class="h-full w-full shadow">
    </div>

    <div class="w-full md:w-1/3 flex flex-col flex-grow flex-shrink">
        <div class="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow-lg">
            <p class="w-full text-gray-600 text-xs md:text-sm pt-6 px-6">
                {{ lead_post.publish }} by {{ lead_post.author }}</p>
            <div class="w-full font-bold text-xl text-gray-900 px-6">
                <a href="{{ lead_post.get_absolute_url }}">
                    {{ lead_post.title }}
                </a>
            </div>
            <p class="text-gray-800 font-serif text-base px-6 mb-5">
                {{ lead_post.body|truncatewords:80 }}
            </p>
            <p class="text-gray-800 font-serif text-base px-6 mb-5">
                {% for tag in lead_post.tags.all %}
                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                        #{{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %} 
                {% endfor %}</p>
        </div>

        <div class="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow-lg p-6">
            <div class="flex items-center justify-between">
                <img class="w-8 h-8 rounded-full mr-4 avatar" data-tippy-content="Author Name" src="http://i.pravatar.cc/300" alt="Avatar of Author">
                <p class="text-gray-600 text-xs md:text-sm">1 MIN READ</p>
            </div>
        </div>
    </div>
</div>

<!--/Lead Card-->

<!--Posts Container-->

<div class="flex flex-wrap justify-between pt-12 -mx-6">

    <!--1/3 col -->

    {% for post in posts %}
    <div class="w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink">
        <div class="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow-lg">
            <a href="{{ post.get_absolute_url }}" class="flex flex-wrap no-underline hover:no-underline">
                <img src="https://source.unsplash.com/collection/225/800x600" class="h-64 w-full rounded-t pb-6">
                <p class="w-full text-gray-600 text-xs md:text-sm px-6">
                    {{ post.publish }} by {{ post.author }}
                </p>
                <div class="w-full font-bold text-xl text-gray-900 px-6">
                    {{ post.title }}
                </div>
                <p class="text-gray-800 font-serif text-base px-6 mb-5">
                    {{ post.body|truncatewords:50 }} 
                </p>
                <p class="w-full text-gray-600 text-xs md:text-sm pt-6 px-6">
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            #{{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %} <!-- теги отделяются запятыми -->
                    {% endfor %}
                </p>
            </a>
        </div>
        <div class="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow-lg p-6">
            <div class="flex items-center justify-between">
                <img class="w-8 h-8 rounded-full mr-4 avatar" data-tippy-content="Author Name" src="http://i.pravatar.cc/300" alt="Avatar of Author">
                <p class="text-gray-600 text-xs md:text-sm">1 MIN READ</p>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static %}

{% block title %}My blog{% endblock %}
{% block css %}
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/> <!--Replace with your tailwind.css once created-->
    
<style>:root{::-webkit-scrollbar{height:10px;width:10px}::-webkit-scrollbar-track{background:#efefef;border-radius:6px}::-webkit-scrollbar-thumb{background:#d5d5d5;border-radius:6px}::-webkit-scrollbar-thumb:hover{background:#c4c4c4}}</style>
{% endblock %}

{% block content %}
<body class="bg-gray-200 font-sans leading-normal tracking-normal">
	<!--Header-->
	<div class="w-full m-0 p-0 bg-cover bg-bottom" style="background-image:url('{% static "/img/cover.jpg" %}'); height: 60vh; max-height:460px;">
			<div class="container max-w-4xl mx-auto pt-16 md:pt-32 text-center break-normal">
				<!--Title-->
					<p class="text-white font-extrabold text-3xl md:text-5xl">
						👻 Ghostwind CSS
					</p>
					<p class="text-xl md:text-2xl text-gray-500">Welcome to my Blog</p>
					<p class="text-xs md:text-xs text-gray-500">Total posts: {% total_posts %}</p>
			</div>
		</div>
		
		<!--Container-->
		<div class="container px-4 md:px-0 max-w-6xl mx-auto -mt-32">
			
			<div class="mx-0 sm:mx-6">
				
				<!--Nav-->
				<nav class="mt-0 w-full">
					<div class="container mx-auto flex items-center">
						
						<div class="flex w-1/2 pl-4 text-sm">
							<ul class="list-reset flex justify-between flex-1 md:flex-none items-center">
								<li class="mr-2">
								<a class="inline-block py-2 px-2 text-white no-underline hover:underline" href="post.html">POST</a>
								</li>
								<li class="mr-2">
								<a class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:underline py-2 px-2" href="multimenu post.html">MULTIMENU POST</a>
								</li>
								<li class="mr-2">
								<a class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:underline py-2 px-2" href="#">LINK</a>
								</li>
								<li class="mr-2">
								<a class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:underline py-2 px-2" href="post_vue.html">POST_VUE</a>
								</li>
							</ul>
						</div>


						<div class="flex w-1/2 justify-end content-center">		
							<a class="inline-block text-gray-500 no-underline hover:text-white hover:text-underline text-center h-10 p-2 md:h-auto md:p-4 avatar" data-tippy-content="@twitter_handle" href="https://twitter.com/intent/tweet?url=#">
								<svg class="fill-current h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path d="M30.063 7.313c-.813 1.125-1.75 2.125-2.875 2.938v.75c0 1.563-.188 3.125-.688 4.625a15.088 15.088 0 0 1-2.063 4.438c-.875 1.438-2 2.688-3.25 3.813a15.015 15.015 0 0 1-4.625 2.563c-1.813.688-3.75 1-5.75 1-3.25 0-6.188-.875-8.875-2.625.438.063.875.125 1.375.125 2.688 0 5.063-.875 7.188-2.5-1.25 0-2.375-.375-3.375-1.125s-1.688-1.688-2.063-2.875c.438.063.813.125 1.125.125.5 0 1-.063 1.5-.25-1.313-.25-2.438-.938-3.313-1.938a5.673 5.673 0 0 1-1.313-3.688v-.063c.813.438 1.688.688 2.625.688a5.228 5.228 0 0 1-1.875-2c-.5-.875-.688-1.813-.688-2.75 0-1.063.25-2.063.75-2.938 1.438 1.75 3.188 3.188 5.25 4.25s4.313 1.688 6.688 1.813a5.579 5.579 0 0 1 1.5-5.438c1.125-1.125 2.5-1.688 4.125-1.688s3.063.625 4.188 1.813a11.48 11.48 0 0 0 3.688-1.375c-.438 1.375-1.313 2.438-2.563 3.188 1.125-.125 2.188-.438 3.313-.875z"></path></svg>
							</a>
							<a class="inline-block text-gray-500 no-underline hover:text-white hover:text-underline text-center h-10 p-2 md:h-auto md:p-4 avatar" data-tippy-content="#facebook_id" href="https://www.facebook.com/sharer/sharer.php?u=#">
								<svg class="fill-current h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path d="M19 6h5V0h-5c-3.86 0-7 3.14-7 7v3H8v6h4v16h6V16h5l1-6h-6V7c0-.542.458-1 1-1z"></path></svg>
							</a>
						</div>

					</div>
				</nav>

				<div class="bg-gray-200 w-full text-xl md:text-2xl text-gray-800 leading-normal rounded-t">
					
				<!--Posts-->	
				{% if page_number == 1 and tag == none %}
					{% show_latest_posts 4 %}
					<h3>Most commented posts.</h3>
					{% get_most_commented_posts as most_commented_posts %}
					<ul>
						{% for post in most_commented_posts %}
						<li>
							<a href="{{ post.get_absolute_url }}" class="flex flex-wrap no-underline hover:underline">
								{{ post.title }}</a>
						</li>
						{% endfor %}
					</ul>
				{% else %}
				
				<!--Posts Container-->
				<div class="flex flex-wrap justify-between pt-12 -mx-6">

				{% for post in posts %}
					<!--1/2 col -->
					<div class="w-full md:w-1/2 p-6 flex flex-col flex-grow flex-shrink">
						<div class="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow-lg">
							<a href="{{ post.get_absolute_url }}" class="flex flex-wrap no-underline hover:no-underline">
								<img src="https://source.unsplash.com/collection/3657445/800x600" class="h-full w-full rounded-t pb-6">
								<p class="w-full text-gray-600 text-xs md:text-sm px-6">
									{{ post.publish }} by {{ post.author }}</p>
								<div class="w-full font-bold text-xl text-gray-900 px-6">
									{{ post.title }}</div>
								<p class="text-gray-800 font-serif text-base px-6 mb-5">
									{{ post.body|truncatewords:50 }} 
								</p>
								<p class="w-full text-gray-600 text-xs md:text-sm pt-6 px-6">
									{% for tag in post.tags.all %}
										<a href="{% url "blog:post_list_by_tag" tag.slug %}">
											#{{ tag.name }}
										</a>
										{% if not forloop.last %}, {% endif %} <!-- теги отделяются запятыми -->
									{% endfor %}
								</p>
							</a>
						</div>
						<div class="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow-lg p-6">
							<div class="flex items-center justify-between">
								<img class="w-8 h-8 rounded-full mr-4 avatar" data-tippy-content="Author Name" src="http://i.pravatar.cc/300" alt="Avatar of Author">
								<p class="text-gray-600 text-xs md:text-sm">1 MIN READ</p>
							</div>
						</div>
					</div>
				{% endfor %}
				</div>
				<!--/ Post Content-->
				{% endif %}
			</div>
			{% include "./includes/pagination.html" with page=posts %}
			{% include "./includes/subscribe.html" %}
		</div>
	</div>

<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/tippy.js@6"></script>
<script>
	//Init tooltips
	tippy('.avatar')
</script>

</body>
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}

{% endblock %}

mysite/blog/templates/blog/post/share.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Share</title>
  <link rel="stylesheet" href="{% static "/css/mail.css" %}">
</head>

<body>
  <!-- partial:index.partial.html -->
  
    <div id="container"></div>
    <script id="template">
      <div class="contact-wrapper">
          <div {% if sent %}class="envelope active"{% else %}class="envelope" {% endif %}>
            <div class="back paper"></div>
            <div class="content">
              <div class="form-wrapper">
                <form method="post">
                  <div class="top-wrapper">
                    <div class="input">
                      <label>Name</label>
                      {{ form.name }}
                    </div>
                    
                    <div class="input">
                      <label>Email</label>
                      {{ form.email }}
                    </div>
                  </div>
                  <div class="bottom-wrapper">
                    <div class="input">
                      <label>To</label>
                      {{ form.to }}
                    </div>
                    <div class="input">
                      <label>Message</label>
                      {{ form.comments }}
                    </div>
                    {% csrf_token %}
                    <div class="submit">
                      <div>
                        <input class="submit-card" type="submit" value="Send">
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <div class="front paper"></div>
          </div>
          
        </div>
      
    </script>
    
  

  <script src='https://cdn.jsdelivr.net/npm/ractive@0.9'></script>
  <script  src="/static/js/mail.js"></script>

</body>
</html>